create table public.authorized_students (
  id bigint generated by default as identity not null,
  name text not null,
  email text not null,
  created_at timestamp with time zone not null default now(),
  constraint authorized_students_pkey primary key (id),
  constraint authorized_students_email_key unique (email)
) TABLESPACE pg_default;