import { Video } from './model';

export const VIDEOS: Video[] = [
  {
    id: '1',
    title: 'Como acessar a plataforma da Elia',
    description: 'Tutorial completo sobre como acessar e navegar pela plataforma da Elia.',
    duration: '5 min',
    url: 'https://youtu.be/ws5t1YCwKFc',
    thumbnail: '/api/placeholder/400/225',
  },
  {
    id: '2',
    title: 'Visão geral agentes Elia',
    description:
      'Visão geral de todos os agentes disponíveis na plataforma Elia e suas funcionalidades.',
    duration: '8 min',
    url: 'https://youtu.be/6fwxcWfWrNM',
    thumbnail: '/api/placeholder/400/225',
  },
  {
    id: '3',
    title: 'Agente de Marketing',
    description: 'Como utilizar o agente de marketing para estratégias e campanhas publicitárias.',
    duration: '6 min',
    url: 'https://youtu.be/-JdbKa4B8bg',
    thumbnail: '/api/placeholder/400/225',
  },
  {
    id: '4',
    title: 'Agente Promptador',
    description: 'Aprenda a usar o agente promptador para criar prompts eficientes e precisos.',
    duration: '7 min',
    url: 'https://youtu.be/eLz_1-KXyYQ',
    thumbnail: '/api/placeholder/400/225',
  },
  {
    id: '5',
    title: 'Agente Tradução e ChatGPT Plus',
    description: 'Como utilizar o agente de tradução e integração com ChatGPT Plus.',
    duration: '9 min',
    url: 'https://youtu.be/JxP72ypsv78',
    thumbnail: '/api/placeholder/400/225',
  },
  {
    id: '6',
    title: 'Agente Diagnóstico',
    description: 'Utilize o agente de diagnóstico para análise e identificação de problemas.',
    duration: '6 min',
    url: 'https://youtu.be/_jqzIMUcYTQ',
    thumbnail: '/api/placeholder/400/225',
  },
  {
    id: '7',
    title: 'Agente Tese',
    description:
      'Como trabalhar com o agente de tese para desenvolvimento de argumentos jurídicos.',
    duration: '8 min',
    url: 'https://youtu.be/UzvqEhrBjrI',
    thumbnail: '/api/placeholder/400/225',
  },
  {
    id: '8',
    title: 'Agente Contrato',
    description: 'Utilize o agente de contrato para criação e revisão de documentos contratuais.',
    duration: '7 min',
    url: 'https://youtu.be/G6ZIfIKTY00',
    thumbnail: '/api/placeholder/400/225',
  },
  {
    id: '9',
    title: 'Agente Jurisprudência',
    description: 'Como usar o agente de jurisprudência para pesquisa e análise de casos.',
    duration: '6 min',
    url: 'https://youtu.be/3GWdnmxUQ2Y',
    thumbnail: '/api/placeholder/400/225',
  },
  {
    id: '10',
    title: 'Agente Petição Inicial',
    description: 'Tutorial completo sobre o agente de petição inicial para processos jurídicos.',
    duration: '8 min',
    url: 'https://youtu.be/6ylhhroYQLc',
    thumbnail: '/api/placeholder/400/225',
  },
  {
    id: '11',
    title: 'Agente Revisor',
    description: 'Como utilizar o agente revisor para análise e correção de documentos.',
    duration: '5 min',
    url: 'https://youtu.be/oyz6vSJtrjo',
    thumbnail: '/api/placeholder/400/225',
  },
  {
    id: '12',
    title: 'Agente Petição Incidental',
    description: 'Aprenda a usar o agente de petição incidental para procedimentos específicos.',
    duration: '7 min',
    url: 'https://youtu.be/AN4Tg0mJqSA',
    thumbnail: '/api/placeholder/400/225',
  },
];
